# Apache aliases
alias aprestart='sudo /etc/init.d/apache2 restart'
alias apreload='sudo /etc/init.d/apache2 restart'
alias apenable='sudo a2ensite'
alias aphttpd='sudo vi /etc/apache2/httpd.conf'

# Git tab completion
source ~/.git-completion.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
PS1='\[\033[1;33m\]\u\[\033[0m\]@\[\033[1;33m\]\h \[\033[0m\]\w\[\033[1;33m\]$(__git_ps1 " %s")\[\033[0m\] \$ '

# git command aliases
alias gst='git status'
alias gb='git branch'
alias gch='git checkout'
alias gchm='git checkout master'
alias gchb='git checkout -b'
alias grem='git remote show'
alias gfetch='git fetch origin'
alias gcommit='git commit -m'
alias gchange='git whatchanged -p --'

# Personal customizations
alias ehosts='sudo vi /etc/hosts'
alias ebashlocal='vim ~/.bash_profile'
alias ebash='vim ~/webwork/ryana804.com/html/files/bash_profile'
alias rbash='. ~/.bash_profile'
alias evimrc='vim ~/webwork/ryana804.com/html/files/vimrc'
alias evimrclocal='vim ~/.vimrc'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias gr='grep -r'
alias vim='vim -p'

# Shell scripts, etc
alias elogs='tail -f /var/log/apache2/error_log'
